model:
  verbose: false

data:
  dataset:
    games_genres: /media/felipe/32740855-6a5b-4166-b047-c8177bb37be1/snes-back/vmdb/deepseek_genres.csv
    path: /media/felipe/32740855-6a5b-4166-b047-c8177bb37be1/snes-back/vmdb/nintendo-snes-spc

  data_loader:
    batch_size: 2
    num_workers: 2

train:
  num_epochs: 100
  iters_per_epoch: 10
  eval_iters: 10
  lr: 1e-4
  weight_decay: 1e-2